# This is a sample build configuration for Haskell.
# Do not use tabs to indent your configuration
# You can specify a custom docker image from Dockerhub
# for your build environment
image: haskell:latest

definitions:
  caches:
    cabal-new: ~/.cabal/store
    cabal-old: ~/.cabal/store

pipelines:
  default:
    - parallel:
      - step:
          name: "Haskell Latest"
          caches:
            - cabal-new
          script: &commonScript
            - ghc --version && cabal --version
            - cabal new-update
            - cabal new-install --enable-tests --only-dependencies
            - cabal new-configure --enable-tests -v2
            - cabal new-build
            - cabal new-test
      - step:
          name: "Haskell 8.2"
          image: haskell:8.2
          caches:
            - cabal-old
          script: &v8OrLowerCommonScript
            - ghc --version && cabal --version
            - cabal sandbox init
            - cabal update
            - cabal install --enable-tests --only-dependencies
            - cabal configure --enable-tests -v2
            - cabal build
            - cabal test
      - step:
          name: "Haskell 8.0"
          image: haskell:8.0
          caches:
            - cabal-old
          script: *v8OrLowerCommonScript
      - step:
          name: "Haskell 7.10"
          image: haskell:7.10
          caches:
            - cabal-old
          script: *v8OrLowerCommonScript
      - step:
          name: "Haskell 7.8"
          image: haskell:7.8
          caches:
            - cabal-old
          script: *v8OrLowerCommonScript
